---
title: "Manuscripts Under Review"
description-meta: "Manuscripts under peer review by Emmanuel Kubuafor and collaborators"
title-block-banner: false
css: custom.css
---

<!-- Academic Icons -->
{{< include /files/includes/_academic.qmd >}}



- **Kubuafor, E.**, Baidoo, D., Duah, A., Amevor, R., Okeke, O. J., Quaye, D., & Appiah, P. O. (2025). *Latent Spatial Heterogeneity in U.S. Cancer Mortality: A Multi-Site Clustering and Spatial Autocorrelation Analysis.*  
  [arXiv:2508.12188](https://arxiv.org/abs/2508.12188){.colored-link}

- **Kubuafor, E.**, Baidoo, D., Okeke, O. J., Amevor, R., Arhin, G., & Korley, J. T. (2025). *Evaluation of Time Series Forecasting Models for Predicting Lung Cancer Mortality Rates in the United States: A Comparison with Altuhaifa (2023) Study.*  
  [arXiv:2508.16052](https://arxiv.org/abs/2508.16052){.colored-link}

- Baidoo, D., **Kubuafor, E.**, Joshua, O. O., Osarfo, S. F., Agyei-Owusu, F. A., Akuoko-Frimpong, J., & Benyi, B. (2025). *Comparing Malaria Trends in the Comoros Islands: ARIMA Modeling and Retrospective Analysis.*  
  [arXiv:2508.16018](https://arxiv.org/abs/2508.16018){.colored-link}

- Amevor, R., **Kubuafor, E.**, Baidoo, D., Salifu, J., Gonnage, K. M., & Okeke, O. J. (2025). *Integrative Prognostic Modeling of Breast Cancer Survival with Gene Expression and Clinical Data.*  
  [arXiv:2508.16740](https://arxiv.org/abs/2508.16740){.colored-link}

- Baidoo, D., **Kubuafor, E.**, Osarfo, S. F., Agyei-Owusu, F. A., Frimpong, J. A., Amevor, R., & Aboagye, F. (2025). *Bayesian Hierarchical Methods for Surveillance of Cervical Dystonia Treatments.*  
  [arXiv:2508.15762](https://arxiv.org/abs/2508.15762){.colored-link}

- Okeke, O. J., Nwaogu, C., Oladoyin, O. O., **Kubuafor, E.**, Baidoo, D., Akinyemi, T., & Fabunmi, I. A. (2025). *Assessing the Influence of Locational Suitability on the Spatial Distribution of Household Wealth in Bernalillo County, NM.*  
  [arXiv:2510.11048](https://arxiv.org/abs/2510.11048){.colored-link}

- Okeke, O. J., **Kubuafor, E.** (2025). *Optimizing Cattle Ranching Locations in Chaves County, New Mexico: A GIS-based Assessment of Ecological Resources and Spatial Relationships to Active and Abandoned Oil and Gas Wells.*  
  [Link](https://drive.google.com/file/d/1nuZqnttcz7ASJOGLB7X3kU9kq_0h9Iu3/view?usp=sharing){.colored-link}

---

<!-- Social Share Buttons -->
{{< include /files/includes/_socialshare.qmd >}}
